// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-9V9lhv3xkrlo40I30lWAlwyQtV6YX4',
    appId: '1:337882112045:web:5ecdbb3d39e531965158a4',
    messagingSenderId: '337882112045',
    projectId: 'whos-the-imposter-a6ffe',
    authDomain: 'whos-the-imposter-a6ffe.firebaseapp.com',
    storageBucket: 'whos-the-imposter-a6ffe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJQQyxpGvIVeT-PNECC5ISqpKgoU5JCAY',
    appId: '1:337882112045:android:5adc681c537744425158a4',
    messagingSenderId: '337882112045',
    projectId: 'whos-the-imposter-a6ffe',
    storageBucket: 'whos-the-imposter-a6ffe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf0jDEueSXPRbaC3If1Q6OCjI3hEaOXcI',
    appId: '1:337882112045:ios:6f8c554e909460fa5158a4',
    messagingSenderId: '337882112045',
    projectId: 'whos-the-imposter-a6ffe',
    storageBucket: 'whos-the-imposter-a6ffe.firebasestorage.app',
    iosBundleId: 'com.example.whosTheImposter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf0jDEueSXPRbaC3If1Q6OCjI3hEaOXcI',
    appId: '1:337882112045:ios:6f8c554e909460fa5158a4',
    messagingSenderId: '337882112045',
    projectId: 'whos-the-imposter-a6ffe',
    storageBucket: 'whos-the-imposter-a6ffe.firebasestorage.app',
    iosBundleId: 'com.example.whosTheImposter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz-9V9lhv3xkrlo40I30lWAlwyQtV6YX4',
    appId: '1:337882112045:web:f134cc8f1b5c62eb5158a4',
    messagingSenderId: '337882112045',
    projectId: 'whos-the-imposter-a6ffe',
    authDomain: 'whos-the-imposter-a6ffe.firebaseapp.com',
    storageBucket: 'whos-the-imposter-a6ffe.firebasestorage.app',
  );
}
